### ISSUE TITLE
Integration of Closure-based Builder.

### ISSUE THREAD

**Issue by itbrunoms** [juarezfranco/builder_when#2]
Overview:
The current implementation of builder_when in Flutter provides conditional rendering based on a specified condition. However, to enhance its flexibility and allow more dynamic customization, the addition of a closure-based builder functionality is proposed.

Objective:
The objective is to extend the functionality of builder_when by incorporating a builder in closure format, enabling users to define custom widget structures based on conditions by passing in a closure.

Proposed Solution:

Introduce a new parameter builder of type Widget Function() within the builder_when component.
This builder will accept a closure that returns a widget tree defining the structure to be rendered when the condition is met.
Update the component's logic to utilize the provided closure when the specified condition holds true.
Expected Behavior:
Users will gain the ability to define custom widget structures using a closure-based approach within builder_when. This enhancement will allow for more versatile and dynamic rendering based on conditions.

Benefits:

Enhanced Customization: Users can specify complex widget structures based on conditions.
Improved Usability: Simplifies the process of conditionally rendering widgets in a more expressive manner.
Consistency with Flutter Paradigm: Aligns with Flutter's widget-building patterns, enhancing familiarity.
Additional Notes:

Compatibility considerations for existing implementations should be addressed for a seamless transition.
Unit tests and updated documentation will be necessary to reflect these changes and guide users in utilizing the new functionality effectively.
References:

Link to relevant Flutter documentation or resources on conditional widget building and closures.
Any related discussions or issues in the project repository related to conditional rendering.
Steps to Implement:

Introduce the builder parameter in the builder_when component's constructor.
Modify the internal rendering logic to incorporate the provided closure when the condition is satisfied.
Update documentation with usage examples demonstrating the new capability.
The addition of a closure-based builder in builder_when will significantly augment its capabilities, offering users more control over conditional widget rendering.

Your insights and suggestions on this proposed enhancement are highly appreciated for refining the implementation approach.

**Comment by juarezfranco** [comment]
You are right

**Comment by juarezfranco** [comment]
#1 
#3
